CREATE TABLE products (
  product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_name TEXT NOT NULL,
  price numeric NOT NULL,
  image TEXT NOT NULL,
  category TEXT NOT NULL,
  available_quantity SMALLINT NOT NULL,
  description TEXT NOT NULL,
  measurements TEXT NOT NULL,
  how_made TEXT NOT NULL,
  care_instructions TEXT NOT NULL
);